config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :articles

  get 'examples/comun'

  get 'welcome/index'

  post':controller(/:action(/:id))'

   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/example.rb
class Example < ActiveRecord::Base
	#attr_accessible :nombre 
end

app/models/user.rb
class User < ActiveRecord::Base
	#attr_accessible :nombre, :bio, :cuempleanos, :programa, 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def comun
  	@nombre = params[:nombre_usuario]
  	@email = params[:email_usuario]
  	@nombres= Example.last
  	@ejemplo= Example.create({nombre: @nombre, email:@email})
  	
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombre, :password, :email, :bio, :progama, :cumpleanos, :work_time)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #layout 'ejemplo'
  #layout 'comun'
  def index
  	@tutor='Juan Candia'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def is_number?(n)
		if n=~ /^\d+$/
			true
		else
			false	
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_formulario.html.erb
<html>
<head>
	<title>Formulario propio</title>
</head>
<body>
	<%= form_for(@user) do |u| %>
	<div class='field'>
		<%= u.label :nombre %>
		<%= u.text_field :nombre %>
	</div>
	<div class='field'>
		<%= u.label :bio %>
		<%= u.text_area :bio, :cols=>30, rows: 20 %>
	</div>
	<div class='field'>
		<%= u.label :programa %>
		<%= u.check_box :programa, checked: "checked" %>
	</div>
<% end %>

</body>
<footer>bandera</footer>
</html>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/examples/comun.html.erb
<html>
<head>
	<title>Vista comun</title>
</head>
<body>
	<div id='ingreso'>
		<h1>Vista de comun  <%= @nombre %></h1>
			<%= form_tag :action => 'comun' do %>
		<p>Nombre: 
		<%= text_field_tag 'nombre_usuario', @name %></p>
		<p>Email:
		<%= text_field_tag 'email_usuario', @email %></p>
		<%= submit_tag 'Registar' %>
		<% end %>
	</div>	
	
		<p><%= @nombres.email %></p>
	
</body>
<footer>vista de controlador example</footer>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>	
</head>
<body>
	<h1>Codigo facilito</h1>
<%= yield %>

</body>
</html>

app/views/layouts/ejemplo.html.erb
<html>
<head>
	<title>Ejemplo layouts</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>	
</head>
<body>
	<h1>Esto es un ejemplo de otro layouts</h1>
	<p>ejemplo.html.erb</p>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome Layouts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>	
</head>
<body>

	<h1>Welcome Layouts</h1>


</body>
<footer>
dirección: welcome.html.erb
</footer>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :progama %><br>
    <%= f.check_box :progama %>
  </div>
  <div class="field">
    <%= f.label :cumpleanos %><br>
    <%= f.date_select :cumpleanos %>
  </div>
  <div class="field">
    <%= f.label :work_time %><br>
    <%= f.time_select :work_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_formulario.html.erb
<html>
<head>
	<title>Formulario propio</title>
</head>
<body>
	<%= form_for(@user) do |u| %>
	<div class='field'>
		<% nombres = {'Ramon Candia'=>'Juan', 'Cualquier cosa'=>'cualquiercosa','email'=>'email'} %>	
		<fieldset>
				<% lista = nombres.sort %>
				<%= u.label :nombre  %>
				<%= u.select :nombre, lista  %>
		</fieldset>

	</div>
	<div class='field'>
		<%= u.label :nombre %>
		<%= u.text_field :nombre %>
	</div>
	<div class='field'>
		<%= u.label :bio %>
		<%= u.text_area :bio, :cols=>30, rows: 20 %>
	</div>
	<div class='field'>
		<%= u.label :Programa %>
		<%= u.check_box :programa, checked: "checked" %>
	</div>
	<div class='field'>
		<%= u.label :cumpleanos  %>
		<%= u.date_select :cumpleanos, start_year: 1990, end_year: 2014  %>
	</div>	
<% end %>

<% a= 'hola'  %>
		<% if is_number?(a)  %>
			<b><%= a %></b>
			<% else  %>
				<b>Enviaste palabras</b>
		<% end %>	

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Password</th>
      <th>Email</th>
      <th>Bio</th>
      <th>Progama</th>
      <th>Cumpleanos</th>
      <th>Work time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= user.progama %></td>
        <td><%= user.cumpleanos %></td>
        <td><%= user.work_time %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'formulario' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Progama:</strong>
  <%= @user.progama %>
</p>

<p>
  <strong>Cumpleanos:</strong>
  <%= @user.cumpleanos %>
</p>

<p>
  <strong>Work time:</strong>
  <%= @user.work_time %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<html>
<head>
	<title>Primer controlador</title>
</head>
<body>
	<h1>Welcome#index</h1>
	<p>Primera vista usando g controller</p>
	<p>Tutor:<%= @tutor %></p>
</body>
<footer>
by <%= @tutor %>; index.html.erb
</footer>
</html>